### ISSUE TITLE
Error when press enter on a simple input messagebox

### ISSUE THREAD

**Issue by jpolvora** [gasparesganga/jquery-message-box#2] opened 2016-10-14 22:06 UTC
I have a very simple inputbox:

``` js
    $.MessageBox({
        input: 'default value',
        message: "Digite o valor da pesquisa"
    }).done(function (data) {
        //console.log(data)
        //if click the button OK with the mouse, everything runs ok.
        //but if press enter while typing something in the textbox, causes error
    });
```

The messagebox shows normally, but when I type some text and press enter, the messagebox closes as expected but the code fails and stops javascript execution.

The problem doesn't occur if i click in the OK button manually.
Details of error:

Chrome 53
MessageBox 2.0

The error is in line [423](https://github.com/gasparesganga/jquery-message-box/blob/master/src/messagebox.js#L423) of messagebox.js

``` js
instance.deferred.resolve(inputValues, event.data.name);
```

where event.data is undefined when pressing enter.

**Comment by jpolvora** [comment] 2016-10-14 22:09
Solution:
Changing this line:

``` js
instance.deferred.resolve(inputValues, event.data.name);
```

To:

``` js
instance.deferred.resolve(inputValues, event.data ? event.data.name : "");
```

solves the problem, but I don't know if there any consequences.
I will let you know if I find issues after changing this line.

**Comment by gasparesganga** [comment] 2016-10-18 13:33
I can't reproduce the behaviour you have described. It seems everything works just fine using the code you provided in your first post, without any modification at all.
I can't test with Chrome 53, but with Chrome 54 there are no issues. The `name` is always set and there is no difference in the handler called by clicking on the button or pressing the enter key.

Are you using some other code which modifies the MessageBox DOM?

**Comment by gasparesganga** [comment] 2016-11-18 10:03
Since I cannot reproduce the issue, you haven't answered back in a month and the issue doesn't seem to exist at all, I am closing this.

**Closed as completed by gasparesganga** 2016-11-18 10:03 UTC
Labels: can't reproduce
